### ISSUE TITLE
Seprate settings per flight modes

### ISSUE THREAD

**Issue by borisp2** [jfrickmann/SoarOTX#4]
Hi Jasper, first of all i would like to thank you for such great work what you did with SoarOTX - i love it. I have one question for you. Did you think to have separate 4.Another mixes per Flight Modes? Primary what I am looking for is to have different settings for Diff, Snapflap, Ail2Rud per flight modes. Thank you. Boris

**Comment by jfrickmann** [comment]
Hi Boris,
My name is Jesper; not Jasper. With that detail out of the way ;-)
In my program, the GVs all use "FM0 value", because I prefer to keep things simple and use the same mixes in all flight modes. But if you want to change it, just set the relevant GVs to use "Own value". The menu will adjust for the selected FM, so that should "just work".

Jesper

**Comment by borisp2** [comment]
;) Ah sorry for misspelling your name Jesper. Thank you for answer it works as i expected! :) Boris
